#!/bin/bash
## Init Harp git
cd /var/www
git remote remove origin
git remote add origin $REPO
git fetch origin
git reset --hard origin/master
NODE_ENV=production
nave use stable harp server /var/www --port 80
