#!/bin/bash
## Init Harp git
set -e
cd /var/www
git remote remove origin
git remote add origin $REPO
echo git remote add origin $REPO
git fetch origin
git reset --hard origin/master
nave use stable harp server /var/www --port 80
