#!/bin/bash
## Init Harp git
set -e
cd /var/www
git remote remove origin
git remote add origin $REPO
echo git remote add origin $REPO
git fetch origin
git reset --hard origin/master
nave use stable /.nave/installed/0.10.32/bin/harp server /var/www --port 80
